# Exploratory notebook

Very messy - first cut at examining the data.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
# Load the raw data
df = pd.read_json('../data/raw/data.json')

In [7]:
# Explore the data
df.head()

response
data       [[S1901_C01_010MA, S1901_C01_009E, S1901_C02_0...
objectId                                   ACSST5Y2021.S1901
tableName                                              S1901

In [17]:
# df['response']['data'][1]
len(df['response']['data'])

5

There are 5 arrays in the response, with the first one being non data. The remaining 4 should correspond to the following zipcodes:
1. `77055`
2. `77027`
3. `77024`
4. `77056`

Now I'll try and find the specific index that gives me the income data.

In [18]:
zip1, zip2, zip3, zip4 = df['response']['data'][1], df['response']['data'][2], df['response']['data'][3], df['response']['data'][4]

In [34]:
# 77027

# median income = 96,834

for i in range(len(zip2)):
    if zip2[i] == '96834':
        print(i)

# i = 161

161


In [37]:
# 77056

# median income = 101,563

for i in range(len(zip4)):
    if zip4[i] == '101563':
        print(i)

# i = 161

161


In [39]:
# 77024

# median income = 122,979

for i in range(len(zip1)):
    if zip1[i] == '122979':
        print(i)

# i = 161

161


In [40]:
# 77055

# median income = 64,277

for i in range(len(zip3)):
    if zip3[i] == '64277':
        print(i)

# i = 161

161


Looks like `161` is the index for **Median income (dollars)**

In [41]:
# trying with cleveland and 2019
df_cleveland = pd.read_json('../data/raw/cleveland-income-2019.json')

zip_cleveland = df_cleveland['response']['data'][1]

In [42]:
zip_cleveland[161] #16,999

'16999'

In [88]:
# trying with 2016
df_cle_inc_16 = pd.read_json('../data/raw/cleveland-income-2016.json')

zip_cle_inc_16 = df_cle_inc_16['response']['data'][1]
zip_cle_inc_16[161] # 14414, correct

'14414'

In [89]:
# trying with 2011
df_cle_inc_11 = pd.read_json('../data/raw/cleveland-income-2011.json')

zip_cle_inc_11 = df_cle_inc_11['response']['data'][1]
zip_cle_inc_11[161] # 14227, correct

'14227'

In [57]:
# trying with cleveland and 2019
df_cle_pop = pd.read_json('../data/raw/cleveland-pop-2017.json')

zip_cle_pop = df_cle_pop['response']['data'][1]

In [58]:
for i in range(len(zip_cle_pop)):
    if zip_cle_pop[i] == '20541':
        print(i)

95
243
334
350
527
613
676
691


In [65]:
df_cle_pop2 = pd.read_json('../data/raw/cleveland-pop-2013.json')

zip_cle_pop2 = df_cle_pop2['response']['data'][1]

for i in range(len(zip_cle_pop2)):
    if zip_cle_pop2[i] == '22593':
        print(i)

126
130
228
316
361
401
431
565


In [68]:
df_cle_pop3 = pd.read_json('../data/raw/cleveland-pop-2015.json')



In [74]:
zip_cle_pop3 = df_cle_pop3['response']['data'][1]

for i in range(len(zip_cle_pop3)):
    if zip_cle_pop3[i] == '22465':
        print(i)

138
142
240
328
373
413
443
582


In [10]:
df_cle_pop_new_2021 = pd.read_json('../data/raw/cleveland-pop-new-2021.json')
zip_cle_pop_new_2021 = df_cle_pop_new_2021['response']['data'][1]

for i in range(len(zip_cle_pop_new_2021)):
    if zip_cle_pop_new_2021[i] == '18945':
        print(i)

277


In [78]:
df_hou_pop_13 = pd.read_json('../data/raw/houston-pop-2013.json')
zip_hou_pop_13 = df_hou_pop_13['response']['data'][1]

for i in range(len(zip_hou_pop_13)):
    if zip_hou_pop_13[i] == '35367':
        print(i)

# 270

270


In [80]:
df_hou_pop_15 = pd.read_json('../data/raw/houston-pop-2015.json')
zip_hou_pop_15 = df_hou_pop_15['response']['data'][1]

for i in range(len(zip_hou_pop_15)):
    if zip_hou_pop_15[i] == '37042':
        print(i)

# 270

270


In [81]:
df_hou_pop_19 = pd.read_json('../data/raw/houston-pop-2019.json')
zip_hou_pop_19 = df_hou_pop_19['response']['data'][1]

for i in range(len(zip_hou_pop_19)):
    if zip_hou_pop_19[i] == '38190':
        print(i)

# 277
# they made a change sometime between 2015 and 19

277


In [83]:
df_hou_pop_18 = pd.read_json('../data/raw/houston-pop-2018.json')
zip_hou_pop_18 = df_hou_pop_18['response']['data'][1]

for i in range(len(zip_hou_pop_18)):
    if zip_hou_pop_18[i] == '38379':
        print(i)

# 277
# they made a change sometime between 2015 and 18

277


In [8]:
df_hou_pop_17 = pd.read_json('../data/raw/houston-pop-2017.json')
zip_hou_pop_17 = df_hou_pop_17['response']['data'][1]

for i in range(len(zip_hou_pop_17)):
    if zip_hou_pop_17[i] == '38110':
        print(i)

# 277

277


In [5]:
# zipcode 77024

df_hou_pop_16 = pd.read_json('../data/raw/houston-pop-2016.json')
zip_hou_pop_16 = df_hou_pop_16['response']['data'][1]

# total population
for i in range(len(zip_hou_pop_16)):
    if zip_hou_pop_16[i] == '37867':
        print(i)

# 270

270


For **population**: up until and including 2016 = `270`, 2017 and onward = `277`

In [6]:
# median age
for i in range(len(zip_hou_pop_16)):
    if zip_hou_pop_16[i] == '44.1':
        print(i)

# 140

140


In [9]:
# median age
for i in range(len(zip_hou_pop_17)):
    if zip_hou_pop_17[i] == '44.3':
        print(i)

# 111
# the same change occurs at the 2017 mark

111


In [12]:
# 44112

for i in range(len(zip_cle_pop_new_2021)):
    if zip_cle_pop_new_2021[i] == '40.9':
        print(i)

# 111, since it's 2017 onward

111


Testing car ownership

In [3]:
df_cle_car_2021 = pd.read_json('../data/raw/cle-car-2021.json')
zip_cle_car_21 = df_cle_car_2021['response']['data'][1]

for i in range(len(zip_cle_car_21)):
    if zip_cle_car_21[i] == '55.0':
        print(i)

# 114


114


In [4]:
df_cle_car_16 = pd.read_json('../data/raw/cle-car-2016.json')
zip_cle_car_16 = df_cle_car_16['response']['data'][1]

for i in range(len(zip_cle_car_16)):
    if zip_cle_car_16[i] == '54.1':
        print(i)

# 114


114


In [9]:
df_hou_car_12 = pd.read_json('../data/raw/hou-car-2012.json')
zip_hou_car_12 = df_hou_car_12['response']['data'][1]

for i in range(len(zip_hou_car_12)):
    if zip_hou_car_12[i] == '8.0':
        print(i)

# 114


114


In [10]:
df_hou_car_16 = pd.read_json('../data/raw/hou-car-2016.json')
zip_hou_car_16 = df_hou_car_16['response']['data'][1]

for i in range(len(zip_hou_car_16)):
    if zip_hou_car_16[i] == '19.2':
        print(i)

# 114, 138, 969


114
138
969


### Testing job ops now

In [3]:
df_hou_job_12 = pd.read_json('../data/raw/hou-job-12.json')
zip_hou_job_12 = df_hou_job_12['response']['data'][1]

for i in range(len(zip_hou_job_12)):
    if zip_hou_job_12[i] == '2276':
        print(i)

# 15

15


In [4]:
df_cle_job_17 = pd.read_json('../data/raw/cle-job-17.json')
zip_cle_job_17 = df_cle_job_17['response']['data'][1]

for i in range(len(zip_cle_job_17)):
    if zip_cle_job_17[i] == '509':
        print(i)

# 15

15


### Testing household splits

In [21]:
df_cle_house_21 = pd.read_json('../data/raw/cle-house-21.json')
zip_cle_house_21 = df_cle_house_21['response']['data'][1]

stats = {
    '15.1': 'Married Couple',
    '8.5': 'Couple',
    '24.6': 'Single Male',
    '16.4': 'Single Male, alone',
    '51.8': 'Single Female',
    '30.4': 'Single Female, alone',
}

for i in range(len(zip_cle_house_21)):
    if zip_cle_house_21[i] in stats:
        print(stats[zip_cle_house_21[i]], ':', i)

Single Female : 121
Single Male, alone : 222
Couple : 379
Single Male : 439
Married Couple : 602
Single Female, alone : 1094


Trying a new dataset for households

In [27]:
curr_df = pd.read_json('../data/raw/cle-house-new-21.json')
curr_zip = curr_df['response']['data'][1]

stats = {'15.1': 'Married Couple', '51.6': 'Non-family', '10.4': 'Single Male, Family', '22.9': 'Single Female, Family',
}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Single Female, Family : 13
Non-family : 346
Married Couple : 863
Single Male, Family : 877


In [28]:
curr_df = pd.read_json('../data/raw/hou-house-new-21.json')
curr_zip = curr_df['response']['data'][1]

stats = {'31.8': 'Married Couple', '61.5': 'Non-family', '2.1': 'Single Male, Family', '4.7': 'Single Female, Family',
}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Single Female, Family : 13
Single Male, Family : 265
Single Female, Family : 341
Non-family : 346
Single Male, Family : 478
Single Female, Family : 532
Single Male, Family : 558
Single Male, Family : 805
Single Male, Family : 838
Married Couple : 863
Single Male, Family : 877
Single Male, Family : 880


Houston and Cleveland have the same indices for 2021 at the very least - they may differ between years but geographies seems consistent.

In [23]:
curr_df = pd.read_json('../data/raw/cle-house-new-19.json')
curr_zip = curr_df['response']['data'][1]

stats = {'17.9': 'Married Couple', '50.1': 'Non-family', '6.4': 'Single Male, Family', '25.6': 'Single Female, Family',
}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Single Female, Family : 13
Non-family : 346
Single Male, Family : 802
Married Couple : 863
Single Male, Family : 877


In [24]:
curr_df = pd.read_json('../data/raw/cle-house-new-15.json')
curr_zip = curr_df['response']['data'][1]

stats = {'18.5': 'Married Couple', '48.9': 'Non-family', '5.5': 'Single Male, Family', '27.0': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Non-family : 11
Married Couple : 31
Single Female, Family : 118
Single Male, Family : 174


In [25]:
curr_df = pd.read_json('../data/raw/cle-house-new-14.json')
curr_zip = curr_df['response']['data'][1]

stats = {'18.3': 'Married Couple', '48.3': 'Non-family', '5.7': 'Single Male, Family', '27.8': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Non-family : 11
Single Male, Family : 24
Married Couple : 31
Single Female, Family : 118
Single Male, Family : 174


In [26]:
curr_df = pd.read_json('../data/raw/cle-house-new-12.json')
curr_zip = curr_df['response']['data'][1]

stats = {'19.5': 'Married Couple', '46.0': 'Non-family', '5.6': 'Single Male, Family', '28.8': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Non-family : 11
Married Couple : 31
Single Female, Family : 120
Single Male, Family : 177


In [3]:
curr_df = pd.read_json('../data/raw/hou-house-new-12.json')
curr_zip = curr_df['response']['data'][1]

stats = {'28.7': 'Married Couple', '63.8': 'Non-family', '3.3': 'Single Male, Family', '4.2': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Single Male, Family : 2
Non-family : 11
Married Couple : 31
Single Female, Family : 120
Single Male, Family : 154
Single Male, Family : 177
Single Female, Family : 210
Single Female, Family : 439


In [4]:
# checking 2016
curr_df = pd.read_json('../data/raw/hou-house-new-16.json')
curr_zip = curr_df['response']['data'][1]

stats = {'30.5': 'Married Couple', '62.4': 'Non-family', '2.7': 'Single Male, Family', '4.5': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Non-family : 11
Married Couple : 31
Single Female, Family : 118
Single Male, Family : 174
Single Male, Family : 422


In [5]:
# checking 2017
curr_df = pd.read_json('../data/raw/hou-house-new-17.json')
curr_zip = curr_df['response']['data'][1]

stats = {'34.2': 'Married Couple', '60.0': 'Non-family', '1.9': 'Single Male, Family', '3.9': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Single Female, Family : 13
Single Male, Family : 181
Single Male, Family : 209
Non-family : 346
Single Male, Family : 409
Single Female, Family : 419
Single Female, Family : 473
Single Male, Family : 753
Married Couple : 863
Single Male, Family : 877
Single Female, Family : 879


In [7]:
# checking 2013
curr_df = pd.read_json('../data/raw/hou-house-new-13.json')
curr_zip = curr_df['response']['data'][1]

stats = {'28.1': 'Married Couple', '63.7': 'Non-family', '3.6': 'Single Male, Family', '4.5': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Non-family : 11
Married Couple : 31
Single Female, Family : 118
Single Male, Family : 151
Single Male, Family : 174
Single Female, Family : 395
Single Female, Family : 398
Single Female, Family : 448


In [8]:
# checking 2011
curr_df = pd.read_json('../data/raw/hou-house-new-11.json')
curr_zip = curr_df['response']['data'][1]

stats = {'32.4': 'Married Couple', '61.7': 'Non-family', '1.6': 'Single Male, Family', '4.2': 'Single Female, Family',}

for i in range(len(curr_zip)):
    if curr_zip[i] in stats:
        print(stats[curr_zip[i]], ':', i)

Non-family : 11
Married Couple : 31
Single Female, Family : 120
Single Male, Family : 177
Single Female, Family : 223
Single Male, Family : 239
Single Female, Family : 405
Single Female, Family : 408
Single Male, Family : 424
Single Female, Family : 436
Single Female, Family : 460
