"""Module to preprocess the raw data for machine learning models.

This module includes functions to clean, transform, and feature engineer the raw data file(s)
generated by `make_dataset.py`. The preprocessed data will be saved in the `data/processed/` 
directory with a specific file name. The module may also include splitting the data into 
training and validation sets.

Functions:
    remove_duplicates(df): Removes duplicate rows from a Pandas DataFrame.
    handle_missing_values(df): Fills missing values in a Pandas DataFrame using various methods.
    feature_engineer(df): Creates new features or transforms existing ones in a Pandas DataFrame.
    split_data(df): Splits a Pandas DataFrame into training and validation sets.

Example usage:
    remove_duplicates(df)
    handle_missing_values(df)
    feature_engineer(df)
    split_data(df)

"""
